apiVersion: apps/v1
kind: Deployment
metadata:  
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yaml
    kompose.version: 1.29.0 (997957870)
  creationTimestamp: null
  labels:
    io.kompose.service: tracegen
  name: tracegen
  namespase: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tracegen
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yaml
        kompose.version: 1.29.0 (997957870)
      creationTimestamp: null
      labels:
        io.kompose.network/jaeger-default: "true"
        io.kompose.service: tracegen
    spec:
      containers:
        - args:
            - -duration
            - 10s
            - -workers
            - "3"
            - -pause
            - 250ms
          env:
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: http://jaeger-collector:14268/api/traces
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: jaeger:4318
          image: jaegertracing/jaeger-tracegen:latest
          name: tracegen
          resources: {}
      restartPolicy: Always
